package org.example;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.example.Main.getProductList;
import static org.example.Main.myJoinStringList;
import static org.junit.jupiter.api.Assertions.*;

class myJoinTest {
    List<String> productList = List.of(
            "Safco Value Mate Series Steel Bookcases, Baked Enamel Finish on Steel, Gray",
            "Newell 342",
            "Avery Legal 4-Ring Binder",
            "Decoflex Hanging Personal Folder File, Blue",
            "Zoom Telephonics V.92.V.44 Controllerless Modem",
            "Deluxe Heavy-Duty Vinyl Round Ring Binder",
            "Xerox 1966",
            "Acco Expandable Hanging Binders",
            "Bush Westfield Collection Bookcases, Dark Cherry Finish, Fully Assembled",
            "Westinghouse Mesh Shade Clip-On Gooseneck Lamp, Black",
            "Astroparche® Fine Business Paper",
            "Recycled Interoffice Envelopes with Re-Use-A-Seal® Closure, 10 x 13",
            "Fellowes EZ Multi-Media Keyboard",
            "GBC Standard Therm-A-Bind Covers",
            "Rediform Voice Mail Log Books",
            "DAX Contemporary Wood Frame with Silver Metal Mat, Desktop, 11 x 14 Size",
            "80 Minute CD-R Spindle, 100/Pack - Staples",
            "SouthWestern Bell FA970 Digital Answering Machine with Time/Day Stamp",
            "StarTAC Series",
            "Eureka Recycled Copy Paper 8 1/2 x 11",
            "Ream",
            "Xerox 1981",
            "SimpliFile™ Personal File, Black Granite, 15w x 6-15/16d x 11-1/4h",
            "Office Star - Task Chair with Contemporary Loop Arms",
            "GBC Instant Report Kit",
            "Belkin 107-key enhanced keyboard, USB/PS/2 interface",
            "Belkin ErgoBoard™ Keyboard",
            "Ampad® Poly Cover Wirebound Steno Book, 6 x 9 Assorted Colors, Gregg Ruled",
            "Chromcraft 48 x 96 Racetrack Double Pedestal Table",
            "Acme® Elite Stainless Steel Scissors",
            "Belkin 19 Vented Equipment Shelf, Black",
            "Epson C62 Color Inkjet Printer",
            "Wausau Papers Astrobrights® Colored Envelopes",
            "Xerox 1945",
            "KI Conference Tables",
            "Global Ergonomic Managers Chair",
            "Staples Jumbo Liquid Stix Highlighters, Assorted, 6/Pack",
            "Contemporary Borderless Frame",
            "Eldon Jumbo ProFile™ Portable File Boxes Graphite/Black",
            "Newell 325",
            "Newell 330",
            "Fellowes Mobile Numeric Keypad, Graphite",
            "Newell 32",
            "Xerox 21",
            "Dot Matrix Printer Tape Reel Labels, White, 5000/Box",
            "Newell 344",
            "Fellowes Staxonsteel® Drawer Files",
            "ACCOHIDE® 3-Ring Binder, Blue, 1",
            "ACCOHIDE® 3-Ring Binder, Blue, 1",
            "Acco Four Pocket Poly Ring Binder with Label Holder, Smoke, 1",
            "R300LX",
            "6161i",
            "Verbatim DVD-R 4.7GB authoring disc",
            "Acme Design Line 8 Stainless Steel Bent Scissors w/Champagne Handles, 3-1/8 Cut",
            "Office Star - Contemporary Task Swivel chair with 2-way adjustable arms, Plum",
            "Sony 80-Minute CD-R Spindle, 50/Pack",
            "#10 Self-Seal White Envelopes",
            "Howard Miller 13 Diameter Pewter Finish Round Wall Clock",
            "Howard Miller 11-1/2 Diameter Grantwood Wall Clock",
            "TDK 4.7GB DVD-R",
            "Acme® Elite Stainless Steel Scissors",
            "Wirebound Message Books, Four 2 3/4 x 5 Forms per Page, 200 Sets per Book",
            "Eldon Radial Chair Mat for Low to Medium Pile Carpets",
            "Avery® Metallic Poly Binders",
            "Newell Chalk Holder",
            "Polycom VoiceStation 100",
            "Xerox 1978",
            "C-Line Peel & Stick Add-On Filing Pockets, 8-3/4 x 5-1/8, 10/Pack",
            "SAFCO PlanMaster Heigh-Adjustable Drafting Table Base, 43w x 30d x 30-37h, Black",
            "HON® 5400 Series Task Chairs for Big and Tall",
            "Eldon L Workstation Diamond Chairmat",
            "Xerox 1920",
            "TeleTAC Series",
            "Adesso Tru-Form Ergonomic Keyboard",
            "Xerox 1989",
            "Xerox 1942",
            "Letter Size Cart",
            "OIC Bulk Pack Metal Binder Clips",
            "Xerox 1969",
            "Euro-Pro Shark Turbo Vacuum",
            "Fellowes Basic 104-Key Keyboard, Platinum",
            "Anderson Hickey Conga Table Tops & Accessories",
            "Contico 72 H Heavy-Duty Storage System",
            "Tenex Antistatic Computer Chair Mats",
            "Sanford Liquid Accent Highlighters",
            "StarTAC 3000",
            "Round Ring Binders",
            "Hon 2090 “Pillow Soft” Series Mid Back Swivel/Tilt Chairs",
            "Fellowes Smart Design 104-Key Enhanced Keyboard, PS/2 Adapter, Platinum",
            "V60",
            "Avery 489",
            "Avery 487",
            "Xerox 191",
            "Grip Seal Envelopes",
            "Nu-Form 106-Key Ergonomic Keyboard w/ Touchpad",
            "5185i",
            "Disposable Triple-Filter Dust Bags",
            "Global Leather Executive Chair",
            "Global Highback Leather Tilter in Burgundy",
            "Premier Automatic Letter Opener",
            "Chromcraft Bull-Nose Wood Round Conference Table Top, Wood Base",
            "Wilson Jones International Size A4 Ring Binders",
            "Binder Posts",
            "i390",
            "Acco Pocket Keypad",
            "Canon CP1213D 12-Digit Heavy Duty Printing Calculator",
            "Xerox 1895",
            "Dixon Ticonderoga Core-Lock Colored Pencils, 48-Color Set",
            "Novimex Fabric Task Chair",
            "Newell 34",
            "Safco Industrial Wire Shelving System",
            "Howard Miller 13 Diameter Goldtone Round Wall Clock",
            "Tenex V2T-RE Standard Weight Series Chair Mat, 45 x 53, Lip 25 x 12",
            "Bush Advantage Collection® Racetrack Conference Table",
            "Wilson Jones Turn Tabs Binder Tool for Ring Binders",
            "Embossed Ink Jet Note Cards",
            "Fellowes Bankers Box™ Recycled Super Stor/Drawer®",
            "Personal Filing Tote with Lid, Black/Gray",
            "Binney & Smith inkTank™ Erasable Desk Highlighter, Chisel Tip, Yellow, 12/Box",
            "Micro Innovations 104 Keyboard",
            "Tripp Lite TLP810NET Broadband Surge for Modem/Fax",
            "Accohide Poly Flexible Ring Binders",
            "Epson LQ-2080 Dot Matrix Printer",
            "Xerox 1959",
            "Acco Pressboard Covers with Storage Hooks, 14 7/8 x 11, Executive Red",
            "Binder Posts",
            "Staples® General Use 3-Ring Binders",
            "#10 Gummed Flap White Envelopes, 100/Box",
            "Staples SlimLine Pencil Sharpener",
            "Micro Innovations 104 Keyboard",
            "Unpadded Memo Slips",
            "Office Star - Contemporary Task Swivel Chair",
            "Newell 351",
            "T18",
            "Harbour Creations 67200 Series Stacking Chairs",
            "Sanford Pocket Accent® Highlighters",
            "Black Print Carbonless 8 1/2 x 8 1/4 Rapid Memo Book",
            "Avery® Durable Plastic 1 Binders",
            "Xerox 2000",
            "StarTAC ST7868",
            "Avery 513",
            "Wirebound Message Book, 4 per Page",
            "Acco PRESSTEX® Data Binder with Storage Hooks, Dark Blue, 9 1/2 X 11",
            "Geographics Note Cards, Blank, White, 8 1/2 x 11",
            "Storex Dura Pro™ Binders",
            "TeleTAC Series",
            "Avery File Folder Labels",
            "Imation Printable White 80 Minute CD-R Spindle, 50/Pack",
            "Panasonic KX-P1150 Dot Matrix Printer",
            "Electrix Architect's Clamp-On Swing Arm Lamp, Black",
            "Newell 324",
            "Xerox 1976",
            "KI Adjustable-Height Table",
            "DAX Charcoal/Nickel-Tone Document Frame, 5 x 7",
            "Woodgrain Magazine Files by Perma",
            "Stride Job 150 Highlighters, Chisel Tip, Assorted Colors",
            "Tennsco Commercial Shelving",
            "Safco Commercial Shelving",
            "SpineVue® Locking Slant-D® Ring Binders by Cardinal",
            "Acco 7-Outlet Masterpiece Power Center, Wihtout Fax/Phone Line Protection",
            "Bretford “Just In Time” Height-Adjustable Multi-Task Work Tables",
            "Security-Tint Envelopes",
            "Ampad #10 Peel & Seel® Holiday Envelopes",
            "Tensor Brushed Steel Torchiere Floor Lamp",
            "Xerox 1927",
            "Staples Recycled White 1-Part Blank Computer Paper",
            "Adesso Programmable 142-Key Keyboard",
            "Imation 3.5 IBM Formatted Diskettes, 10/Box",
            "Advantus Push Pins",
            "Xerox 199",
            "Sanford Colorific® Eraseable Coloring Pencils, 12 Count",
            "Microsoft Office Keyboard",
            "Fellowes Superior 10 Outlet Split Surge Protector",
            "Bevis Oval Conference Table, Walnut",
            "Zipper Ring Binder Pockets",
            "Xerox 23",
            "Strathmore Photo Frame Cards",
            "Gyration Ultra Cordless Optical Suite",
            "7190",
            "Prang Dustless Chalk Sticks",
            "Xerox 1989",
            "Eldon Spacemaker® Box, Quick-Snap Lid, Clear",
            "Premier Elliptical Ring Binder, Black",
            "Microsoft Multimedia Keyboard T2297",
            "Sony 3.5 DS/HD Diskettes, 100/Pack",
            "Fellowes Econo/Stor® Drawers",
            "Dixon Ticonderoga Core-Lock Colored Pencils, 48-Color Set",
            "Wausau Papers Astrobrights® Colored Envelopes",
            "Riverside Palais Royal Lawyers Bookcase, Royale Cherry Finish",
            "Hon iLevel™ Computer Training Table",
            "Avery® Durable Slant Ring Binders With Label Holder",
            "Xerox 1920",
            "Xerox 1920",
            "Adams Telephone Message Book W/Dividers/Space For Phone Numbers, 5 1/4X8 1/2, 300/Messages",
            "Iris® 3-Drawer Stacking Bin, Black",
            "Bush Somerset Collection Bookcase"
    );

    @Test
    void myJoinTest() {
        String joinedProductList = String.join(",\n", productList);
        String myJoinedProductList = myJoinStringList(productList);
        assertEquals(joinedProductList, myJoinedProductList);
    }

    @Test
    void getProductListTest() {
        assertEquals(productList, getProductList());
    }
}
